/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Font;
import java.text.DecimalFormat;

/**
 *
 * @author 92017403
 * Jamie Burrows
 * 15/12/16
 */
public class CalculatorFrame extends javax.swing.JFrame {

    private double total1 = 0.0;
    private double total2 = 0.0;
    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
        panExtended.setVisible(false);
        setSize(340,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrView = new javax.swing.ButtonGroup();
        bgrFont = new javax.swing.ButtonGroup();
        bgrRound = new javax.swing.ButtonGroup();
        msgMessage = new javax.swing.JOptionPane();
        txtOutput = new javax.swing.JTextField();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnReciprical = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        panExtended = new javax.swing.JPanel();
        btnSin = new javax.swing.JButton();
        btnAsin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnAcos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnAtan = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        radDegrees = new javax.swing.JRadioButton();
        radRadians = new javax.swing.JRadioButton();
        mnuMenu = new javax.swing.JMenuBar();
        mnuView = new javax.swing.JMenu();
        mnuBasic = new javax.swing.JRadioButtonMenuItem();
        mnuExtended = new javax.swing.JRadioButtonMenuItem();
        mnuFont = new javax.swing.JMenu();
        mnuPlain = new javax.swing.JRadioButtonMenuItem();
        mnuBold = new javax.swing.JRadioButtonMenuItem();
        mnuRound = new javax.swing.JMenu();
        radDec0 = new javax.swing.JRadioButtonMenuItem();
        radDec1 = new javax.swing.JRadioButtonMenuItem();
        radDec2 = new javax.swing.JRadioButtonMenuItem();
        radDec3 = new javax.swing.JRadioButtonMenuItem();
        radDec4 = new javax.swing.JRadioButtonMenuItem();
        radDec5 = new javax.swing.JRadioButtonMenuItem();
        radDec6 = new javax.swing.JRadioButtonMenuItem();
        radDec7 = new javax.swing.JRadioButtonMenuItem();
        radDec8 = new javax.swing.JRadioButtonMenuItem();
        radDec9 = new javax.swing.JRadioButtonMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();
        mnuHotKeys = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnCA.setText("CA");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });

        btnCE.setText("CE");

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnPoint.setText(".");

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnMultiply.setText("*");

        btnReciprical.setText("1/x");

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnDivide.setText("/");

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnPower.setText("x^y");

        btnChange.setText("+/-");

        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        btnMinus.setText("-");

        btnFactorial.setText("x!");

        panExtended.setPreferredSize(new java.awt.Dimension(285, 285));

        btnSin.setText("sin");

        btnAsin.setText("asin");

        btnCos.setText("cos");

        btnAcos.setText("acos");

        btnTan.setText("tan");

        btnAtan.setText("atan");

        btnPi.setText("PI");

        btnE.setText("E");

        radDegrees.setText("Degrees");

        radRadians.setText("Radians");

        javax.swing.GroupLayout panExtendedLayout = new javax.swing.GroupLayout(panExtended);
        panExtended.setLayout(panExtendedLayout);
        panExtendedLayout.setHorizontalGroup(
            panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExtendedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panExtendedLayout.createSequentialGroup()
                        .addComponent(radDegrees)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radRadians))
                    .addGroup(panExtendedLayout.createSequentialGroup()
                        .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAtan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAcos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAsin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        panExtendedLayout.setVerticalGroup(
            panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExtendedLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radDegrees)
                    .addComponent(radRadians))
                .addGap(50, 50, 50)
                .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        mnuView.setText("View");

        mnuBasic.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        bgrView.add(mnuBasic);
        mnuBasic.setSelected(true);
        mnuBasic.setText("Basic");
        mnuBasic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuBasicItemStateChanged(evt);
            }
        });
        mnuView.add(mnuBasic);

        mnuExtended.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        bgrView.add(mnuExtended);
        mnuExtended.setMnemonic('B');
        mnuExtended.setText("Extended");
        mnuExtended.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuExtendedItemStateChanged(evt);
            }
        });
        mnuView.add(mnuExtended);

        mnuMenu.add(mnuView);

        mnuFont.setText("Font");

        mnuPlain.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        bgrFont.add(mnuPlain);
        mnuPlain.setSelected(true);
        mnuPlain.setText("Plain");
        mnuPlain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuPlainItemStateChanged(evt);
            }
        });
        mnuFont.add(mnuPlain);

        mnuBold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bgrFont.add(mnuBold);
        mnuBold.setText("Bold");
        mnuBold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuBoldItemStateChanged(evt);
            }
        });
        mnuFont.add(mnuBold);

        mnuMenu.add(mnuFont);

        mnuRound.setText("Round");

        bgrRound.add(radDec0);
        radDec0.setText("0");
        radDec0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec0ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec0);

        bgrRound.add(radDec1);
        radDec1.setText("1");
        radDec1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec1ItemStateChanged(evt);
            }
        });
        radDec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDec1ActionPerformed(evt);
            }
        });
        mnuRound.add(radDec1);

        bgrRound.add(radDec2);
        radDec2.setText("2");
        radDec2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec2ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec2);

        bgrRound.add(radDec3);
        radDec3.setText("3");
        radDec3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec3ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec3);

        bgrRound.add(radDec4);
        radDec4.setText("4");
        radDec4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec4ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec4);

        bgrRound.add(radDec5);
        radDec5.setText("5");
        radDec5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec5ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec5);

        bgrRound.add(radDec6);
        radDec6.setText("6");
        radDec6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec6ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec6);

        bgrRound.add(radDec7);
        radDec7.setText("7");
        radDec7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec7ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec7);

        bgrRound.add(radDec8);
        radDec8.setText("8");
        radDec8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec8ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec8);

        bgrRound.add(radDec9);
        radDec9.setSelected(true);
        radDec9.setText("9");
        radDec9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDec9ItemStateChanged(evt);
            }
        });
        mnuRound.add(radDec9);

        mnuMenu.add(mnuRound);

        mnuHelp.setText("Help");

        mnuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        mnuHotKeys.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mnuHotKeys.setText("Hot Keys");
        mnuHotKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHotKeysActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHotKeys);

        mnuMenu.add(mnuHelp);

        setJMenuBar(mnuMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnReciprical, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnPower))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17)
                .addComponent(panExtended, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReciprical, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(panExtended, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radDec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radDec1ActionPerformed

    private void mnuExtendedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuExtendedItemStateChanged
       //Sets Size of Frame and enables visibility of extended panel
        setSize(550, 450);
        panExtended.setVisible(true);
        
        
        
            
        
    }//GEN-LAST:event_mnuExtendedItemStateChanged

    private void mnuBasicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuBasicItemStateChanged
        //Hides extended panel and resizes frame
        setSize(340, 450);
        panExtended.setVisible(false);
    }//GEN-LAST:event_mnuBasicItemStateChanged

    private void mnuPlainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuPlainItemStateChanged
        //Sets txtOutput font to plain
        if (mnuPlain.isSelected()){
            Font oldFont = txtOutput.getFont();
            Font newFont = new Font (oldFont.getName(), Font.PLAIN, oldFont.getSize());
            txtOutput.setFont(newFont);
        }
    }//GEN-LAST:event_mnuPlainItemStateChanged

    private void mnuBoldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuBoldItemStateChanged
        //Sets txtOutput font to Bold
        if (mnuBold.isSelected()){
            Font oldFont = txtOutput.getFont();
            Font newFont = new Font (oldFont.getName(), Font.BOLD, oldFont.getSize());
            txtOutput.setFont(newFont);
        }
    }//GEN-LAST:event_mnuBoldItemStateChanged

    
    
    //The following code sets the decimal places in txtOutput depending on which rounding item is selected from menu
    private void radDec9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec9ItemStateChanged
        //Sets decimal places in txtOutput to 9
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.9f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec9ItemStateChanged

    private void radDec0ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec0ItemStateChanged
        //Sets decimal places in txtOutput to 0
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.0f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec0ItemStateChanged

    private void radDec1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec1ItemStateChanged
        //Sets decimal places in txtOutput to 1 
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.1f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec1ItemStateChanged

    private void radDec2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec2ItemStateChanged
        //Sets decimal places in txtOutput to 2 
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.2f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec2ItemStateChanged

    private void radDec3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec3ItemStateChanged
        //Sets decimal places in txtOutput to 3 
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.3f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec3ItemStateChanged

    private void radDec4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec4ItemStateChanged
        //Sets decimal places in txtOutput to 4
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.4f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec4ItemStateChanged

    private void radDec5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec5ItemStateChanged
        //Sets decimal places in txtOutput to 5
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.5f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec5ItemStateChanged

    private void radDec6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec6ItemStateChanged
        //Sets decimal places in txtOutput to 6
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.6f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec6ItemStateChanged

    private void radDec7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec7ItemStateChanged
        //Sets decimal places in txtOutput to 7
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.7f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec7ItemStateChanged

    private void radDec8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDec8ItemStateChanged
       //Sets decimal places in txtOutput to 8
        DecimalFormat df = new DecimalFormat("##.##");
        txtOutput.setText(String.format("%.8f",Double.parseDouble(txtOutput.getText())));
    }//GEN-LAST:event_radDec8ItemStateChanged

    
    
    private void mnuHotKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHotKeysActionPerformed
        //This sets the message to be displayed in the option pane dialog form when the hot keys menu item is clicked
        msgMessage.showMessageDialog(this, "Ctrl+A - About" + "\nCtrl+K - HotKeys" + "\nCtrl+P - Plain Font" + "\nCtrl+B - Bold Font"+ "\nShift+B - Basic View" + 
        "\nCtrl+E - Extended View" + "\nAlt+P - PI" + "\nAlt+E - E", "Hot Keys", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuHotKeysActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        msgMessage.showMessageDialog(this, "Calculator" + "\nCreated By: Jamie Burrows" + "\n15/12/2016", "About", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuAboutActionPerformed

    
    
    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
//        // This sets the CA button to clear all contents of txtOutput
//        total2=0;
//        txtOutput.setText("");
    }//GEN-LAST:event_btnCAActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        //Sets the text property of btn1 to display the number 1 when clicked
        String btn1Text = txtOutput.getText() + btn1.getText();
        txtOutput.setText(btn1Text);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        //Sets the text property of btn2 to display the number 2 when clicked
        String btn2Text = txtOutput.getText() + btn2.getText();
        txtOutput.setText(btn2Text);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        //Sets the text property of btn3 to display the number 3 when clicked
        String btn3Text = txtOutput.getText() + btn3.getText();
        txtOutput.setText(btn3Text);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        //Sets the text property of btn4 to display the number 4 when clicked
        String btn4Text = txtOutput.getText() + btn4.getText();
        txtOutput.setText(btn4Text);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        //Sets the text property of btn5 to display the number 5 when clicked
        String btn5Text = txtOutput.getText() + btn5.getText();
        txtOutput.setText(btn5Text);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        //Sets the text property of btn6 to display the number 6 when clicked
        String btn6Text = txtOutput.getText() + btn6.getText();
        txtOutput.setText(btn6Text);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        //Sets the text property of btn7 to display the number 7 when clicked
        String btn7Text = txtOutput.getText() + btn7.getText();
        txtOutput.setText(btn7Text);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        //Sets the text property of btn8 to display the number 8 when clicked
        String btn8Text = txtOutput.getText() + btn8.getText();
        txtOutput.setText(btn8Text);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        //Sets the text property of btn9 to display the number 9 when clicked
        String btn9Text = txtOutput.getText() + btn9.getText();
        txtOutput.setText(btn9Text);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
       //Sets the text property of btn0 to display the number 0 when clicked
        String btn0Text = txtOutput.getText() + btn0.getText();
        txtOutput.setText(btn0Text);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
//    total1 = total1 + Double.parseDouble( txtOutput.getText( ) ) ;
//    txtOutput.setText("");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
//        total2 = total1 + Double.parseDouble( txtOutput.getText( ) );
//        txtOutput.setText(Double.toString(total2));
    }//GEN-LAST:event_btnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrFont;
    private javax.swing.ButtonGroup bgrRound;
    private javax.swing.ButtonGroup bgrView;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAcos;
    private javax.swing.JButton btnAsin;
    private javax.swing.JButton btnAtan;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnReciprical;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnTan;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JRadioButtonMenuItem mnuBasic;
    private javax.swing.JRadioButtonMenuItem mnuBold;
    private javax.swing.JRadioButtonMenuItem mnuExtended;
    private javax.swing.JMenu mnuFont;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHotKeys;
    private javax.swing.JMenuBar mnuMenu;
    private javax.swing.JRadioButtonMenuItem mnuPlain;
    private javax.swing.JMenu mnuRound;
    private javax.swing.JMenu mnuView;
    private javax.swing.JOptionPane msgMessage;
    private javax.swing.JPanel panExtended;
    private javax.swing.JRadioButtonMenuItem radDec0;
    private javax.swing.JRadioButtonMenuItem radDec1;
    private javax.swing.JRadioButtonMenuItem radDec2;
    private javax.swing.JRadioButtonMenuItem radDec3;
    private javax.swing.JRadioButtonMenuItem radDec4;
    private javax.swing.JRadioButtonMenuItem radDec5;
    private javax.swing.JRadioButtonMenuItem radDec6;
    private javax.swing.JRadioButtonMenuItem radDec7;
    private javax.swing.JRadioButtonMenuItem radDec8;
    private javax.swing.JRadioButtonMenuItem radDec9;
    private javax.swing.JRadioButton radDegrees;
    private javax.swing.JRadioButton radRadians;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}